version: "3.7"

services:
  db:
    build:
      context: ./dockerfiles/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root-secret
      TZ: Asia/Tokyo

volumes:
  postgres-data:
