// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddUser struct {
	Name    string `json:"name"`
	Kana    string `json:"kana"`
	Address string `json:"address"`
	Email   string `json:"email"`
	Tell    string `json:"tell"`
	Memo    string `json:"memo"`
}

type Hello struct {
	Message string `json:"message"`
}

type User struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Kana    string `json:"kana"`
	Address string `json:"address"`
	Email   string `json:"email"`
	Tell    string `json:"tell"`
	Memo    string `json:"memo"`
}
